services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"
  redis:
    image: redis:alpine
    command: redis-server --requirepass Redis2022!
    ports:
      - "6379:6379"